name: build-and-release
run-name: Blobs build (and release if version tag)

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        arch: [ARM64, X64]
    name: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install nix
        uses: cachix/install-nix-action@v20
      - name: build artifacts
        run: |
          case "${{ matrix.arch }}" in
            X64)
              nix-build --pure -A all
              ;;
            ARM64)
              nix-build -A all --arg pkgs '(import ./nixpkgs.nix { }).pkgsCross.aarch64-multiplatform'
              ;;
          esac
      - name: upload architecture tarball
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.arch }}
          path: ./result/*
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Changes between Tags
        id: changes
        uses: simbo/changes-between-tags-action@v1
      - name: Put changes into temp file
        id: changes-file
        run: |
          echo "${{ steps.changes.outputs.changes }}" > ${{ github.workspace }}-CHANGELOG.txt
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/enclaves-blobs/
      - name: Install pixz
        run: sudo apt-get install -y pixz
      - name: Combine build results
        run: tar -cf - -C enclaves-blobs build-ARM64/aarch64 build-X64/x86_64 --transform "s|build-[^/]*/||" | pixz > enclaves-blobs.txz
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Upload to S3
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          aws s3 cp ${{ github.workspace }}/enclaves-blobs.txz s3://nitro-binaries-test/${VERSION}/
          aws s3 cp ${{ github.workspace }}/enclaves-blobs.txz s3://nitro-binaries-test/latest/
      - name: Release
        uses: softprops/action-gh-release@v2
        id: create_release
        with:
          draft: false
          prerelease: false
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          generate_release_notes: true
          make_latest: true
          files: enclaves-blobs.txz
        env:
          GITHUB_TOKEN: ${{ github.token }}
