name: S3 Binary Upload Test

on: [workflow_dispatch]

env:
  AWS_REGION: eu-central-1
  S3_BUCKET: nitro-binaries-test

jobs:
  upload-test:
    strategy:
      matrix:
        arch: [X64, ARM64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20

      - name: Build and prepare artifacts
        run: |
          OUTDIR="tmp/nitro-binaries/${{ matrix.arch }}"
          mkdir -p "$OUTDIR"
          
          case "${{ matrix.arch }}" in
            X64)
              nix-build --pure -A all
              ;;
            ARM64)
              nix-build -A all --arg pkgs '(import ./nixpkgs.nix { }).pkgsCross.aarch64-multiplatform'
              ;;
          esac
          
          cp -L -r result/* "$OUTDIR/"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload binaries to S3
        run: |
          aws s3 cp tmp/nitro-binaries/${{ matrix.arch }}/ s3://${S3_BUCKET}/${{ matrix.arch }}/ --recursive
